# Generated by Django 3.0.2 on 2020-02-26 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CSKnowledgeBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('expertise_required', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=40)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionandAnswerForum.Question')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CSKnowledgeBase.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRelpy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_header', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('reply_rank', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('expertise_required', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionandAnswerForum.Question')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionExpertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CSKnowledgeBase.Expertise')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionandAnswerForum.Question')),
            ],
            options={
                'unique_together': {('question_id', 'expertise_id')},
            },
        ),
    ]
