# Generated by Django 3.0.2 on 2020-02-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionandAnswerForum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='posted_by',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
