# Generated by Django 2.2.6 on 2020-02-27 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionandAnswerForum', '0003_auto_20200227_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionexpertise',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionandAnswerForum.Question'),
        ),
        migrations.AlterField(
            model_name='questionrelpy',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionandAnswerForum.Question'),
        ),
        migrations.AlterField(
            model_name='questiontopic',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionandAnswerForum.Question'),
        ),
    ]
