# Generated by Django 2.2.6 on 2020-04-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionandAnswerForum', '0003_auto_20200309_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionrelpy',
            name='anonymous',
            field=models.BooleanField(default=True),
        ),
    ]
