# Generated by Django 2.2.6 on 2020-02-27 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionandAnswerForum', '0004_auto_20200227_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='questionexpertise',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionandAnswerForum.Question', to_field='question_id'),
        ),
        migrations.AlterField(
            model_name='questionrelpy',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionandAnswerForum.Question', to_field='question_id'),
        ),
        migrations.AlterField(
            model_name='questiontopic',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuestionandAnswerForum.Question', to_field='question_id'),
        ),
    ]
