# Generated by Django 2.2.6 on 2020-04-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionandAnswerForum', '0004_auto_20200406_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionrelpy',
            name='slug',
            field=models.SlugField(default='header', max_length=40),
            preserve_default=False,
        ),
    ]
