# Generated by Django 2.2.6 on 2020-04-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionandAnswerForum', '0006_auto_20200429_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionrelpy',
            name='reply_rank',
            field=models.IntegerField(default=0),
        ),
    ]
