# Generated by Django 3.0.2 on 2020-02-11 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBaseEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date_last_modified', models.DateTimeField()),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='CSKnowledgeBase.Category')),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatEntryVulnerabilityEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_entry_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exploiting_threat', to='CSKnowledgeBase.KnowledgeBaseEntry')),
                ('vulnerability_entry_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utlized_vulnerability', to='CSKnowledgeBase.KnowledgeBaseEntry')),
            ],
        ),
        migrations.CreateModel(
            name='EntrySubEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry', to='CSKnowledgeBase.KnowledgeBaseEntry')),
                ('subentry_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subentry', to='CSKnowledgeBase.KnowledgeBaseEntry')),
            ],
        ),
        migrations.CreateModel(
            name='AssetEntryVulnerabilityEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_entry_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affected_asset', to='CSKnowledgeBase.KnowledgeBaseEntry')),
                ('vulnerability_entry_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='present_vulnerability', to='CSKnowledgeBase.KnowledgeBaseEntry')),
            ],
        ),
        migrations.CreateModel(
            name='AssetEntryThreatEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_entry_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threatened_asset', to='CSKnowledgeBase.KnowledgeBaseEntry')),
                ('threat_entry_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threating_entry', to='CSKnowledgeBase.KnowledgeBaseEntry')),
            ],
        ),
        migrations.CreateModel(
            name='AssetEntryCountermeasureEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_entry_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protected_asset', to='CSKnowledgeBase.KnowledgeBaseEntry')),
                ('countermeasure_entry_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countermeasure', to='CSKnowledgeBase.KnowledgeBaseEntry')),
            ],
        ),
    ]
